### ISSUE TITLE
configure ReportingServicesService.exe.config

### ISSUE THREAD

**Issue by robertlyson** [mrsquish/AutomationScripts#2]
Hi,

As part of my SSRS deployment, I need to set up `<AppContextSwitchOverrides value="Switch.System.ServiceModel.DisableUsingServicePointManagerSecurityProtocols=false;Switch.System.Net.DontEnableSchUseStrongCrypto=false" />` in `ReportingServicesService.exe.config` as described [here](https://dba.stackexchange.com/a/189176/111234). 

Maybe you have an idea or encountered this before and know how to do this with PS script?

Thanks.

**Comment by mrsquish** [comment]
Hey Robert, looks like a basic, read, modify save of an Xml file (unless I'm missing something). Powershell has some native ways of dealing with Xml. See what you can come up with yourself, and drop me a line if you need some help.

**Comment by robertlyson** [comment]
@mrsquish thanks for your answer. Was hoping there is some installation arg I can pass in. This way I will go with your suggestion, many thanks for looking into this!

**Comment by mrsquish** [comment]
All good mate. This script is far from comprehensive, but was an acculmination of many hours of work that I didn't want anyone else to have to endure :). Feel free to send me a pull request if you find any enhancements.
